theme: jekyll-theme-cayman
title: Welcome
description: <a href="https://federicoghimenti.github.io" target="_blank">click to open the extarnal tab</a>
"[Home](https://federicoghimenti.github.io) [CV](https://federicoghimenti.github.io/cv) [Research](https://federicoghimenti.github.io/research) [Contacts](https://federicoghimenti.github.io/contacts)"
