theme: jekyll-theme-cayman
title: Federico Ghimenti
description: Hello! I am Federico Ghimenti. I am a Physics phD student at Universite de Paris, working under the supervision of Frederic Van Wijland. I am interested in the structural glass transistion, which I investigate using both analytical and numerical techniques. 
