theme: jekyll-theme-cayman
title: Welcome
description: "[Home](https://federicoghimenti.github.io)"  "[CV](https://federicoghimenti.github.io/cv)" "[Research](https://federicoghimenti.github.io/research)" "[Contacts](https://federicoghimenti.github.io/contacts)"
